config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :new, :show, :create ] do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: :true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: :true, presence: :true
  # before_destroy :check_for_doses

  # private

  # def check_for_doses
  #   if doses.any?
  #     errors.add_to_base("cannot delete ingredient while cocktails exist")
  #     return false
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render "new"
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end


# GET index
#     assigns all cocktails as @cocktails (FAILED - 1)
#   GET show
#     assigns the requested cocktail as @cocktail (FAILED - 2)
#   GET new
#     assigns a new cocktail as @cocktail (FAILED - 3)
#   POST create
#     with valid params
#       creates a new Cocktail (FAILED - 4)
#       assigns a newly created cocktail as @cocktail (FAILED - 5)
#       redirects to the created cocktail (FAILED - 6)
#     with invalid params
#       assigns a newly created but unsaved cocktail as @cocktail (FAILED - 7)
#       re-renders the 'new' template (FAILED - 8)

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_restaurant, only: [ :destroy ]
  before_action :set_cocktail, only: [ :new, :create ]

  def new
    @dose = Dose.new

  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_restaurant
    @dose = Dose.find(params[:id])
  end
end



# GET new
#     assigns a new dose as @dose (FAILED - 1)
#   POST create
#     with valid params
#       creates a new Dose (FAILED - 2)
#       assigns a newly created dose as @dose (FAILED - 3)
#       redirects to the created dose (FAILED - 4)
#     with invalid params
#       assigns a newly created but unsaved dose as @dose (FAILED - 5)
#       re-renders the 'new' template (FAILED - 6)
#   DELETE destroy
#     deletes a Dose (FAILED - 7)

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="home-banner">
  <h1>Le Wagon</h1>
<p>
  <span id="banner-typed-text"></span>
</p>
</div>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    </div>
  </div>
    <div class="col-12">
      <h1>All cocktails</h1>
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class='col-4 c' >
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
                <%= link_to cocktail.name, cocktail_path(cocktail) %>
              </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new cocktail</h1>
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "Back", cocktails_path %>

app/views/cocktails/show.html.erb
<h1> Show </h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h2><%= @cocktail.name %></h2>
      <ul class="list-group">
        <% @cocktail.doses.each do |dose| %>
          <li class="list-group-item"><%= dose.ingredient.name   %> : <%= dose.description %>
            <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
              <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
    <div class="col-sm-12 col-md-6">
<%= render "doses/form", cocktail: @cocktail, dose: @dose %>
    </div>
</div>

<%= link_to "Back", cocktails_path %>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= render "form", cocktail: @cocktail, dose: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <div class="ca">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-default navbar-static-top">
        <%= link_to cocktails_path, class: "navbar-brand" do %>
          <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <%= simple_form_for :search, url: cocktails_path, method: :get do |f| %>
              <div class="search-form-control form-group">
                <input class="form-control string required" type="text" name="search[query]" id="search_query" />
                <button name="button" type="submit" class="btn btn-flat">
                  <i class="fas fa-search"></i> Search
                </button>
              </div>
            <% end %>
          </li>

          <li class="nav-item">
        <%= link_to "Add New Cocktail", new_cocktail_path, class: "nav-link" %>
          </li>

        </ul>
      </div>
      </div>
    </div>

    <%= yield %>


      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>
  </body>
</html>